/**
 * Conference metadata - no hardcoded template URLs.
 * Templates are discovered dynamically via the scraper.
 */

export interface ConferenceInfo {
  id: string;
  name: string;
  shortName: string;
  category: "ml" | "nlp" | "vision" | "general" | "journal";
  description: string;
  website: string;
}

export const CONFERENCES: ConferenceInfo[] = [
  // Machine Learning
  {
    id: "neurips",
    name: "NeurIPS",
    shortName: "NeurIPS",
    category: "ml",
    description: "Conference on Neural Information Processing Systems",
    website: "https://neurips.cc",
  },
  {
    id: "icml",
    name: "ICML",
    shortName: "ICML",
    category: "ml",
    description: "International Conference on Machine Learning",
    website: "https://icml.cc",
  },
  {
    id: "iclr",
    name: "ICLR",
    shortName: "ICLR",
    category: "ml",
    description: "International Conference on Learning Representations",
    website: "https://iclr.cc",
  },
  {
    id: "aaai",
    name: "AAAI",
    shortName: "AAAI",
    category: "ml",
    description: "AAAI Conference on Artificial Intelligence",
    website: "https://aaai.org/conference/aaai/",
  },

  // NLP
  {
    id: "acl",
    name: "ACL",
    shortName: "ACL",
    category: "nlp",
    description: "Annual Meeting of the Association for Computational Linguistics",
    website: "https://aclweb.org",
  },
  {
    id: "emnlp",
    name: "EMNLP",
    shortName: "EMNLP",
    category: "nlp",
    description: "Conference on Empirical Methods in Natural Language Processing",
    website: "https://emnlp.org",
  },
  {
    id: "naacl",
    name: "NAACL",
    shortName: "NAACL",
    category: "nlp",
    description: "North American Chapter of the ACL",
    website: "https://naacl.org",
  },

  // Computer Vision
  {
    id: "cvpr",
    name: "CVPR",
    shortName: "CVPR",
    category: "vision",
    description: "IEEE/CVF Conference on Computer Vision and Pattern Recognition",
    website: "https://cvpr.thecvf.com",
  },
  {
    id: "iccv",
    name: "ICCV",
    shortName: "ICCV",
    category: "vision",
    description: "International Conference on Computer Vision",
    website: "https://iccv.thecvf.com",
  },
  {
    id: "eccv",
    name: "ECCV",
    shortName: "ECCV",
    category: "vision",
    description: "European Conference on Computer Vision",
    website: "https://eccv.ecva.net",
  },

  // General / IEEE / ACM
  {
    id: "ieee",
    name: "IEEE Conference",
    shortName: "IEEE",
    category: "general",
    description: "Standard IEEE conference format",
    website: "https://www.ieee.org/conferences/publishing/templates.html",
  },
  {
    id: "acm",
    name: "ACM SIGCONF",
    shortName: "ACM",
    category: "general",
    description: "ACM conference proceedings format",
    website: "https://www.acm.org/publications/proceedings-template",
  },

  // Journals
  {
    id: "jmlr",
    name: "JMLR",
    shortName: "JMLR",
    category: "journal",
    description: "Journal of Machine Learning Research",
    website: "https://jmlr.org/author-info.html",
  },
  {
    id: "arxiv",
    name: "arXiv Preprint",
    shortName: "arXiv",
    category: "journal",
    description: "Clean article format suitable for arXiv submissions",
    website: "https://arxiv.org",
  },
];

export const CATEGORIES = {
  ml: { name: "Machine Learning", icon: "🤖" },
  nlp: { name: "Natural Language Processing", icon: "💬" },
  vision: { name: "Computer Vision", icon: "👁️" },
  general: { name: "General", icon: "📄" },
  journal: { name: "Journals", icon: "📚" },
} as const;

export function getConferencesByCategory(category: ConferenceInfo["category"]) {
  return CONFERENCES.filter((c) => c.category === category);
}

export function getConferenceById(id: string) {
  return CONFERENCES.find((c) => c.id === id.toLowerCase());
}

/**
 * Generate a fallback template when scraping fails
 */
export function generateFallbackTemplate(
  conferenceName: string,
  shortName: string,
): string {
  return `% ${conferenceName} Template
% Generated by MyLeaf - https://myleaf.app
% 
% Note: This is a fallback template. For the official template,
% please visit the conference website.

\\documentclass{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath,amssymb}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage[margin=1in]{geometry}

\\title{Your Paper Title for ${shortName}}
\\author{
  Author One\\\\
  Affiliation One\\\\
  \\texttt{author1@example.com}
  \\and
  Author Two\\\\
  Affiliation Two\\\\
  \\texttt{author2@example.com}
}
\\date{}

\\begin{document}

\\maketitle

\\begin{abstract}
Your abstract goes here. This should be a concise summary of your paper,
typically 150-250 words, describing the problem, your approach, and key results.
\\end{abstract}

\\section{Introduction}
Introduce your research problem and motivation here.

\\section{Related Work}
Discuss relevant prior work and how your contribution differs.

\\section{Method}
Describe your proposed approach or methodology.

\\section{Experiments}
Present your experimental setup and results.

\\subsection{Setup}
Describe datasets, baselines, and evaluation metrics.

\\subsection{Results}
Present your main results with tables and figures.

\\section{Conclusion}
Summarize your contributions and discuss future work.

\\bibliographystyle{plain}
% \\bibliography{references}

\\end{document}
`;
}
